# Generated by Django 5.1.2 on 2024-10-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonscore",
            old_name="Score",
            new_name="score",
        ),
    ]
